"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class WaypointProto(_message.Message):
    """---------- Primitive building blocks ----------"""

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    X_FIELD_NUMBER: _builtins.int
    Y_FIELD_NUMBER: _builtins.int
    Z_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    x: _builtins.float
    y: _builtins.float
    z: _builtins.float
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        x: _builtins.float = ...,
        y: _builtins.float = ...,
        z: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "x", b"x", "y", b"y", "z", b"z"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___WaypointProto: _TypeAlias = WaypointProto  # noqa: Y015

@_typing.final
class SegmentProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    P_START_FIELD_NUMBER: _builtins.int
    P_END_FIELD_NUMBER: _builtins.int
    LENGTH_FIELD_NUMBER: _builtins.int
    V_MIN_FIELD_NUMBER: _builtins.int
    V_MAX_FIELD_NUMBER: _builtins.int
    length: _builtins.float
    v_min: _builtins.float
    v_max: _builtins.float
    @_builtins.property
    def p_start(self) -> Global___WaypointProto: ...
    @_builtins.property
    def p_end(self) -> Global___WaypointProto: ...
    def __init__(
        self,
        *,
        p_start: Global___WaypointProto | None = ...,
        p_end: Global___WaypointProto | None = ...,
        length: _builtins.float = ...,
        v_min: _builtins.float = ...,
        v_max: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["p_end", b"p_end", "p_start", b"p_start"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["length", b"length", "p_end", b"p_end", "p_start", b"p_start", "v_max", b"v_max", "v_min", b"v_min"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SegmentProto: _TypeAlias = SegmentProto  # noqa: Y015

@_typing.final
class LaneProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    WAYPOINTS_FIELD_NUMBER: _builtins.int
    SEGMENTS_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    @_builtins.property
    def waypoints(self) -> _containers.RepeatedCompositeFieldContainer[Global___WaypointProto]: ...
    @_builtins.property
    def segments(self) -> _containers.RepeatedCompositeFieldContainer[Global___SegmentProto]: ...
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        waypoints: _abc.Iterable[Global___WaypointProto] | None = ...,
        segments: _abc.Iterable[Global___SegmentProto] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "segments", b"segments", "waypoints", b"waypoints"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___LaneProto: _TypeAlias = LaneProto  # noqa: Y015

@_typing.final
class FlightIntentionProto(_message.Message):
    """---------- Flight intention ----------"""

    DESCRIPTOR: _descriptor.Descriptor

    DRONE_ID_FIELD_NUMBER: _builtins.int
    UAV_TYPE_FIELD_NUMBER: _builtins.int
    LANE_FIELD_NUMBER: _builtins.int
    V_WAYPOINTS_FIELD_NUMBER: _builtins.int
    T_DES_FIELD_NUMBER: _builtins.int
    SOC_0_FIELD_NUMBER: _builtins.int
    C_BAT_FIELD_NUMBER: _builtins.int
    P_HOVER_FIELD_NUMBER: _builtins.int
    PRIORITY_FIELD_NUMBER: _builtins.int
    OPERATOR_ID_FIELD_NUMBER: _builtins.int
    T_TAKEOFF_FIELD_NUMBER: _builtins.int
    T_LAND_ESTIMATED_FIELD_NUMBER: _builtins.int
    drone_id: _builtins.str
    uav_type: _builtins.str
    t_des: _builtins.float
    soc_0: _builtins.float
    c_bat: _builtins.float
    p_hover: _builtins.float
    priority: _builtins.int
    operator_id: _builtins.str
    t_takeoff: _builtins.float
    """Optional fields — 0.0 means "not provided" """
    t_land_estimated: _builtins.float
    @_builtins.property
    def lane(self) -> Global___LaneProto: ...
    @_builtins.property
    def v_waypoints(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]: ...
    def __init__(
        self,
        *,
        drone_id: _builtins.str = ...,
        uav_type: _builtins.str = ...,
        lane: Global___LaneProto | None = ...,
        v_waypoints: _abc.Iterable[_builtins.float] | None = ...,
        t_des: _builtins.float = ...,
        soc_0: _builtins.float = ...,
        c_bat: _builtins.float = ...,
        p_hover: _builtins.float = ...,
        priority: _builtins.int = ...,
        operator_id: _builtins.str = ...,
        t_takeoff: _builtins.float = ...,
        t_land_estimated: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["lane", b"lane"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["c_bat", b"c_bat", "drone_id", b"drone_id", "lane", b"lane", "operator_id", b"operator_id", "p_hover", b"p_hover", "priority", b"priority", "soc_0", b"soc_0", "t_des", b"t_des", "t_land_estimated", b"t_land_estimated", "t_takeoff", b"t_takeoff", "uav_type", b"uav_type", "v_waypoints", b"v_waypoints"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FlightIntentionProto: _TypeAlias = FlightIntentionProto  # noqa: Y015

@_typing.final
class WaypointTimeEntryProto(_message.Message):
    """---------- Approved plans ----------"""

    DESCRIPTOR: _descriptor.Descriptor

    WAYPOINT_FIELD_NUMBER: _builtins.int
    TIME_FIELD_NUMBER: _builtins.int
    time: _builtins.float
    @_builtins.property
    def waypoint(self) -> Global___WaypointProto: ...
    def __init__(
        self,
        *,
        waypoint: Global___WaypointProto | None = ...,
        time: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["waypoint", b"waypoint"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["time", b"time", "waypoint", b"waypoint"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___WaypointTimeEntryProto: _TypeAlias = WaypointTimeEntryProto  # noqa: Y015

@_typing.final
class ApprovedPlanProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DRONE_ID_FIELD_NUMBER: _builtins.int
    UAV_TYPE_FIELD_NUMBER: _builtins.int
    LANE_FIELD_NUMBER: _builtins.int
    V_WAYPOINTS_FIELD_NUMBER: _builtins.int
    T_LAND_FIELD_NUMBER: _builtins.int
    PAD_ID_FIELD_NUMBER: _builtins.int
    SLOT_INDEX_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    T_DEP_FIELD_NUMBER: _builtins.int
    WAYPOINT_TIMES_FIELD_NUMBER: _builtins.int
    ALGORITHM_FIELD_NUMBER: _builtins.int
    EXPIRES_AT_FIELD_NUMBER: _builtins.int
    drone_id: _builtins.str
    uav_type: _builtins.str
    t_land: _builtins.float
    pad_id: _builtins.str
    slot_index: _builtins.int
    status: _builtins.str
    """'SOFT_RESERVED' | 'COMMITTED'"""
    t_dep: _builtins.float
    algorithm: _builtins.str
    expires_at: _builtins.float
    @_builtins.property
    def lane(self) -> Global___LaneProto: ...
    @_builtins.property
    def v_waypoints(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]: ...
    @_builtins.property
    def waypoint_times(self) -> _containers.RepeatedCompositeFieldContainer[Global___WaypointTimeEntryProto]: ...
    def __init__(
        self,
        *,
        drone_id: _builtins.str = ...,
        uav_type: _builtins.str = ...,
        lane: Global___LaneProto | None = ...,
        v_waypoints: _abc.Iterable[_builtins.float] | None = ...,
        t_land: _builtins.float = ...,
        pad_id: _builtins.str = ...,
        slot_index: _builtins.int = ...,
        status: _builtins.str = ...,
        t_dep: _builtins.float = ...,
        waypoint_times: _abc.Iterable[Global___WaypointTimeEntryProto] | None = ...,
        algorithm: _builtins.str = ...,
        expires_at: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["lane", b"lane"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["algorithm", b"algorithm", "drone_id", b"drone_id", "expires_at", b"expires_at", "lane", b"lane", "pad_id", b"pad_id", "slot_index", b"slot_index", "status", b"status", "t_dep", b"t_dep", "t_land", b"t_land", "uav_type", b"uav_type", "v_waypoints", b"v_waypoints", "waypoint_times", b"waypoint_times"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ApprovedPlanProto: _TypeAlias = ApprovedPlanProto  # noqa: Y015

@_typing.final
class PadProto(_message.Message):
    """---------- Vertiport ----------"""

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    COMPATIBLE_TYPES_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    @_builtins.property
    def compatible_types(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        compatible_types: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["compatible_types", b"compatible_types", "id", b"id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PadProto: _TypeAlias = PadProto  # noqa: Y015

@_typing.final
class SlotEntryProto(_message.Message):
    """Encodes one (pad_id, slot_index) → (drone_id, status) mapping entry"""

    DESCRIPTOR: _descriptor.Descriptor

    PAD_ID_FIELD_NUMBER: _builtins.int
    SLOT_INDEX_FIELD_NUMBER: _builtins.int
    DRONE_ID_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    pad_id: _builtins.str
    slot_index: _builtins.int
    drone_id: _builtins.str
    """empty string when unoccupied"""
    status: _builtins.str
    """'FREE' | 'SOFT' | 'COMMITTED'"""
    def __init__(
        self,
        *,
        pad_id: _builtins.str = ...,
        slot_index: _builtins.int = ...,
        drone_id: _builtins.str = ...,
        status: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["drone_id", b"drone_id", "pad_id", b"pad_id", "slot_index", b"slot_index", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SlotEntryProto: _TypeAlias = SlotEntryProto  # noqa: Y015

@_typing.final
class VertiportStateProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VERTIPORT_ID_FIELD_NUMBER: _builtins.int
    PADS_FIELD_NUMBER: _builtins.int
    SLOT_DURATION_FIELD_NUMBER: _builtins.int
    SLOTS_FIELD_NUMBER: _builtins.int
    vertiport_id: _builtins.str
    slot_duration: _builtins.float
    @_builtins.property
    def pads(self) -> _containers.RepeatedCompositeFieldContainer[Global___PadProto]: ...
    @_builtins.property
    def slots(self) -> _containers.RepeatedCompositeFieldContainer[Global___SlotEntryProto]: ...
    def __init__(
        self,
        *,
        vertiport_id: _builtins.str = ...,
        pads: _abc.Iterable[Global___PadProto] | None = ...,
        slot_duration: _builtins.float = ...,
        slots: _abc.Iterable[Global___SlotEntryProto] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pads", b"pads", "slot_duration", b"slot_duration", "slots", b"slots", "vertiport_id", b"vertiport_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___VertiportStateProto: _TypeAlias = VertiportStateProto  # noqa: Y015

@_typing.final
class MsdEntryProto(_message.Message):
    """---------- System state ----------"""

    DESCRIPTOR: _descriptor.Descriptor

    UAV_TYPE_I_FIELD_NUMBER: _builtins.int
    UAV_TYPE_J_FIELD_NUMBER: _builtins.int
    MSD_FIELD_NUMBER: _builtins.int
    uav_type_i: _builtins.str
    uav_type_j: _builtins.str
    msd: _builtins.float
    def __init__(
        self,
        *,
        uav_type_i: _builtins.str = ...,
        uav_type_j: _builtins.str = ...,
        msd: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["msd", b"msd", "uav_type_i", b"uav_type_i", "uav_type_j", b"uav_type_j"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MsdEntryProto: _TypeAlias = MsdEntryProto  # noqa: Y015

@_typing.final
class BodyLengthEntryProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    UAV_TYPE_FIELD_NUMBER: _builtins.int
    LENGTH_M_FIELD_NUMBER: _builtins.int
    uav_type: _builtins.str
    length_m: _builtins.float
    def __init__(
        self,
        *,
        uav_type: _builtins.str = ...,
        length_m: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["length_m", b"length_m", "uav_type", b"uav_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___BodyLengthEntryProto: _TypeAlias = BodyLengthEntryProto  # noqa: Y015

@_typing.final
class SystemStateProto(_message.Message):
    """SystemStateProto excludes approved_plans and vertiport_state
    (those are passed explicitly in ResolveConflictRequest).
    """

    DESCRIPTOR: _descriptor.Descriptor

    APPROVED_PLANS_FIELD_NUMBER: _builtins.int
    VERTIPORT_STATE_FIELD_NUMBER: _builtins.int
    T_NOW_FIELD_NUMBER: _builtins.int
    MSD_MATRIX_FIELD_NUMBER: _builtins.int
    BODY_LENGTH_FIELD_NUMBER: _builtins.int
    t_now: _builtins.float
    @_builtins.property
    def approved_plans(self) -> _containers.RepeatedCompositeFieldContainer[Global___ApprovedPlanProto]: ...
    @_builtins.property
    def vertiport_state(self) -> Global___VertiportStateProto: ...
    @_builtins.property
    def msd_matrix(self) -> _containers.RepeatedCompositeFieldContainer[Global___MsdEntryProto]: ...
    @_builtins.property
    def body_length(self) -> _containers.RepeatedCompositeFieldContainer[Global___BodyLengthEntryProto]: ...
    def __init__(
        self,
        *,
        approved_plans: _abc.Iterable[Global___ApprovedPlanProto] | None = ...,
        vertiport_state: Global___VertiportStateProto | None = ...,
        t_now: _builtins.float = ...,
        msd_matrix: _abc.Iterable[Global___MsdEntryProto] | None = ...,
        body_length: _abc.Iterable[Global___BodyLengthEntryProto] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["vertiport_state", b"vertiport_state"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["approved_plans", b"approved_plans", "body_length", b"body_length", "msd_matrix", b"msd_matrix", "t_now", b"t_now", "vertiport_state", b"vertiport_state"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SystemStateProto: _TypeAlias = SystemStateProto  # noqa: Y015

@_typing.final
class SCRPConfigProto(_message.Message):
    """---------- Config ----------"""

    DESCRIPTOR: _descriptor.Descriptor

    SOC_MIN_FIELD_NUMBER: _builtins.int
    SLOT_DURATION_SEC_FIELD_NUMBER: _builtins.int
    T_RESPONSE_WINDOW_SEC_FIELD_NUMBER: _builtins.int
    JUNCTION_DIAMETER_M_FIELD_NUMBER: _builtins.int
    DEFAULT_TIMEOUT_BEHAVIOR_FIELD_NUMBER: _builtins.int
    CRUISE_POWER_FACTOR_FIELD_NUMBER: _builtins.int
    MAX_ACCEPTABLE_DELAY_SEC_FIELD_NUMBER: _builtins.int
    soc_min: _builtins.float
    slot_duration_sec: _builtins.float
    t_response_window_sec: _builtins.float
    junction_diameter_m: _builtins.float
    default_timeout_behavior: _builtins.str
    cruise_power_factor: _builtins.float
    max_acceptable_delay_sec: _builtins.float
    def __init__(
        self,
        *,
        soc_min: _builtins.float = ...,
        slot_duration_sec: _builtins.float = ...,
        t_response_window_sec: _builtins.float = ...,
        junction_diameter_m: _builtins.float = ...,
        default_timeout_behavior: _builtins.str = ...,
        cruise_power_factor: _builtins.float = ...,
        max_acceptable_delay_sec: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["cruise_power_factor", b"cruise_power_factor", "default_timeout_behavior", b"default_timeout_behavior", "junction_diameter_m", b"junction_diameter_m", "max_acceptable_delay_sec", b"max_acceptable_delay_sec", "slot_duration_sec", b"slot_duration_sec", "soc_min", b"soc_min", "t_response_window_sec", b"t_response_window_sec"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SCRPConfigProto: _TypeAlias = SCRPConfigProto  # noqa: Y015

@_typing.final
class WaypointTimeResultProto(_message.Message):
    """---------- Results ----------"""

    DESCRIPTOR: _descriptor.Descriptor

    WAYPOINT_ID_FIELD_NUMBER: _builtins.int
    TIME_FIELD_NUMBER: _builtins.int
    waypoint_id: _builtins.str
    time: _builtins.float
    def __init__(
        self,
        *,
        waypoint_id: _builtins.str = ...,
        time: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["time", b"time", "waypoint_id", b"waypoint_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___WaypointTimeResultProto: _TypeAlias = WaypointTimeResultProto  # noqa: Y015

@_typing.final
class ApproveResultProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STATUS_FIELD_NUMBER: _builtins.int
    T_DEP_STAR_FIELD_NUMBER: _builtins.int
    T_LAND_ASSIGNED_FIELD_NUMBER: _builtins.int
    PAD_ID_FIELD_NUMBER: _builtins.int
    SLOT_INDEX_FIELD_NUMBER: _builtins.int
    WAYPOINT_TIMES_FIELD_NUMBER: _builtins.int
    EXPIRES_AT_FIELD_NUMBER: _builtins.int
    DELAY_SECONDS_FIELD_NUMBER: _builtins.int
    DELAY_SOURCE_FIELD_NUMBER: _builtins.int
    ENERGY_ESTIMATE_FIELD_NUMBER: _builtins.int
    SOC_REMAINING_FIELD_NUMBER: _builtins.int
    status: _builtins.str
    """always 'SOFT_RESERVED'"""
    t_dep_star: _builtins.float
    t_land_assigned: _builtins.float
    pad_id: _builtins.str
    slot_index: _builtins.int
    expires_at: _builtins.float
    delay_seconds: _builtins.float
    delay_source: _builtins.str
    energy_estimate: _builtins.float
    soc_remaining: _builtins.float
    @_builtins.property
    def waypoint_times(self) -> _containers.RepeatedCompositeFieldContainer[Global___WaypointTimeResultProto]: ...
    def __init__(
        self,
        *,
        status: _builtins.str = ...,
        t_dep_star: _builtins.float = ...,
        t_land_assigned: _builtins.float = ...,
        pad_id: _builtins.str = ...,
        slot_index: _builtins.int = ...,
        waypoint_times: _abc.Iterable[Global___WaypointTimeResultProto] | None = ...,
        expires_at: _builtins.float = ...,
        delay_seconds: _builtins.float = ...,
        delay_source: _builtins.str = ...,
        energy_estimate: _builtins.float = ...,
        soc_remaining: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["delay_seconds", b"delay_seconds", "delay_source", b"delay_source", "energy_estimate", b"energy_estimate", "expires_at", b"expires_at", "pad_id", b"pad_id", "slot_index", b"slot_index", "soc_remaining", b"soc_remaining", "status", b"status", "t_dep_star", b"t_dep_star", "t_land_assigned", b"t_land_assigned", "waypoint_times", b"waypoint_times"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ApproveResultProto: _TypeAlias = ApproveResultProto  # noqa: Y015

@_typing.final
class RejectResultProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STATUS_FIELD_NUMBER: _builtins.int
    REASON_FIELD_NUMBER: _builtins.int
    EARLIEST_POSSIBLE_FIELD_NUMBER: _builtins.int
    HAS_EARLIEST_POSSIBLE_FIELD_NUMBER: _builtins.int
    DETAIL_FIELD_NUMBER: _builtins.int
    status: _builtins.str
    """always 'REJECTED'"""
    reason: _builtins.str
    earliest_possible: _builtins.float
    """0.0 means "not available" """
    has_earliest_possible: _builtins.bool
    detail: _builtins.str
    def __init__(
        self,
        *,
        status: _builtins.str = ...,
        reason: _builtins.str = ...,
        earliest_possible: _builtins.float = ...,
        has_earliest_possible: _builtins.bool = ...,
        detail: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["detail", b"detail", "earliest_possible", b"earliest_possible", "has_earliest_possible", b"has_earliest_possible", "reason", b"reason", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RejectResultProto: _TypeAlias = RejectResultProto  # noqa: Y015

@_typing.final
class ResolveConflictRequest(_message.Message):
    """---------- RPC messages ----------"""

    DESCRIPTOR: _descriptor.Descriptor

    FI_FIELD_NUMBER: _builtins.int
    APPROVED_PLANS_FIELD_NUMBER: _builtins.int
    VERTIPORT_STATE_FIELD_NUMBER: _builtins.int
    SYSTEM_STATE_FIELD_NUMBER: _builtins.int
    CONFIG_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def fi(self) -> Global___FlightIntentionProto: ...
    @_builtins.property
    def approved_plans(self) -> _containers.RepeatedCompositeFieldContainer[Global___ApprovedPlanProto]: ...
    @_builtins.property
    def vertiport_state(self) -> Global___VertiportStateProto: ...
    @_builtins.property
    def system_state(self) -> Global___SystemStateProto: ...
    @_builtins.property
    def config(self) -> Global___SCRPConfigProto: ...
    def __init__(
        self,
        *,
        fi: Global___FlightIntentionProto | None = ...,
        approved_plans: _abc.Iterable[Global___ApprovedPlanProto] | None = ...,
        vertiport_state: Global___VertiportStateProto | None = ...,
        system_state: Global___SystemStateProto | None = ...,
        config: Global___SCRPConfigProto | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["config", b"config", "fi", b"fi", "system_state", b"system_state", "vertiport_state", b"vertiport_state"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["approved_plans", b"approved_plans", "config", b"config", "fi", b"fi", "system_state", b"system_state", "vertiport_state", b"vertiport_state"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ResolveConflictRequest: _TypeAlias = ResolveConflictRequest  # noqa: Y015

@_typing.final
class ResolveConflictResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    APPROVE_FIELD_NUMBER: _builtins.int
    REJECT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def approve(self) -> Global___ApproveResultProto: ...
    @_builtins.property
    def reject(self) -> Global___RejectResultProto: ...
    def __init__(
        self,
        *,
        approve: Global___ApproveResultProto | None = ...,
        reject: Global___RejectResultProto | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["approve", b"approve", "reject", b"reject", "result", b"result"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["approve", b"approve", "reject", b"reject", "result", b"result"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_result: _TypeAlias = _typing.Literal["approve", "reject"]  # noqa: Y015
    _WhichOneofArgType_result: _TypeAlias = _typing.Literal["result", b"result"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_result) -> _WhichOneofReturnType_result | None: ...

Global___ResolveConflictResponse: _TypeAlias = ResolveConflictResponse  # noqa: Y015
