# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from scrp.proto import scrp_pb2 as scrp__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in scrp_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SCRPServiceStub(object):
    """---------- Service ----------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ResolveConflict = channel.unary_unary(
                '/scrp.SCRPService/ResolveConflict',
                request_serializer=scrp__pb2.ResolveConflictRequest.SerializeToString,
                response_deserializer=scrp__pb2.ResolveConflictResponse.FromString,
                _registered_method=True)


class SCRPServiceServicer(object):
    """---------- Service ----------

    """

    def ResolveConflict(self, request, context):
        """Compute the optimal departure time for a flight intention.
        Returns either an approval (SOFT_RESERVED) or a rejection with reason.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SCRPServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ResolveConflict': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveConflict,
                    request_deserializer=scrp__pb2.ResolveConflictRequest.FromString,
                    response_serializer=scrp__pb2.ResolveConflictResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scrp.SCRPService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scrp.SCRPService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SCRPService(object):
    """---------- Service ----------

    """

    @staticmethod
    def ResolveConflict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrp.SCRPService/ResolveConflict',
            scrp__pb2.ResolveConflictRequest.SerializeToString,
            scrp__pb2.ResolveConflictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
